/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Administration.Statut;
import Utilisateur.Client;
import Administration.StatutClient;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author cdi411
 */
public class JClientMain extends javax.swing.JFrame {

    private int[] mesRowSelect;
    /**
     * Creates new form jf01
     */
    public JClientMain() {
        initComponents();
        
        
        try {
            jComboBoxStatutClient.addItem(null);
            for (Statut stat : StatutClient.getStatut()){
                jComboBoxStatutClient.addItem(stat.getCode());
            }
        } catch (SQLException ex) {
            Logger.getLogger(JClientMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        remplissageJtable();
    }
  
    
   private void remplissageJtable(){
       jTable.setModel(initModel());
       jTable.getColumnModel().getColumn(5).setMinWidth(0);
       jTable.getColumnModel().getColumn(5).setMaxWidth(0);
   }
   
   public void refreshJtable(){
       remplissageJtable();
       for (int i : mesRowSelect){
           jTable.getSelectionModel().addSelectionInterval(i, i);
       }
   }
    
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonModifierStatut = new javax.swing.JButton();
        jLabelClient = new javax.swing.JLabel();
        jTextFieldNomClient = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrenomClient = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxStatutClient = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 40, 73, 90);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTableComponentHidden(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTableComponentResized(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(92, 140, 470, 170);

        jButtonModifierStatut.setText("Modifier Statut");
        jButtonModifierStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierStatutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModifierStatut);
        jButtonModifierStatut.setBounds(230, 340, 140, 23);

        jLabelClient.setText("Rechercher un client par :");
        getContentPane().add(jLabelClient);
        jLabelClient.setBounds(230, 10, 170, 20);

        jTextFieldNomClient.setToolTipText("Utiliser * pour recherche n'importe quel chaine de caractères");
        jTextFieldNomClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomClientActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomClient);
        jTextFieldNomClient.setBounds(180, 40, 260, 30);

        jLabel1.setText("Son nom :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 40, 90, 30);

        jLabel2.setText("Son prénom :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 70, 90, 30);

        jTextFieldPrenomClient.setToolTipText("Utiliser * pour recherche n'importe quel chaine de caractères");
        jTextFieldPrenomClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomClientActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPrenomClient);
        jTextFieldPrenomClient.setBounds(180, 70, 260, 30);

        jLabel3.setText("Son statut :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 100, 90, 30);

        jComboBoxStatutClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatutClientActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxStatutClient);
        jComboBoxStatutClient.setBounds(180, 100, 260, 30);

        setBounds(0, 0, 626, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTableComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableComponentHidden

    private void jTableComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTableComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableComponentResized

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       remplissageJtable();
       
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNomClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomClientActionPerformed

    private void jButtonModifierStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierStatutActionPerformed
        // TODO add your handling code here:
        
        if (jTable.getSelectedRowCount() > 0) {
            ArrayList<Client> mesClients = new ArrayList<>();
            for (int i : jTable.getSelectedRows()) {
                mesClients.add(((Client) jTable.getValueAt(i, 5)));
            }
            this.mesRowSelect = jTable.getSelectedRows();
            new JDialogClient(this, true, mesClients).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Merci de sélectionner au moins un client\n"
                    + " avant de tenter une modification", "Erreur", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButtonModifierStatutActionPerformed

    
    private void jTextFieldPrenomClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomClientActionPerformed

    private void jComboBoxStatutClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatutClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatutClientActionPerformed

    
    
    private DefaultTableModel initModel(){
        
        DefaultTableModel tableModel = new DefaultTableModel();
        
        // Définition des entetes
        tableModel.addColumn("Nom");
        tableModel.addColumn("Prénom");
        tableModel.addColumn("Login");
        tableModel.addColumn("Email");
        tableModel.addColumn("Statut");
        tableModel.addColumn("");
        
       
        String nomRecherche = null;
        if (!jTextFieldNomClient.getText().equals("")){
            nomRecherche = jTextFieldNomClient.getText();
        }
        String prenomRecherche = null;
        if (!jTextFieldPrenomClient.getText().equals("")){
            prenomRecherche = jTextFieldPrenomClient.getText();
        }
        String statutRecherche = null;
        if (jComboBoxStatutClient.getSelectedItem() != null){
            statutRecherche = (jComboBoxStatutClient.getSelectedItem()).toString();
            System.out.println(statutRecherche);
        }
        
        for (Client cli : Client.getSearchListClient(nomRecherche, prenomRecherche, statutRecherche)){
            Vector monVec = new Vector();
            monVec.add(cli.getNomClient());
            monVec.add(cli.getPrenomClient());
            monVec.add(cli.getLoginClient());
            monVec.add(cli.getEmailClient());
            monVec.add(cli.getStatutClient());
            monVec.add(cli);
            tableModel.addRow(monVec);
        }
        
        return tableModel;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JClientMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonModifierStatut;
    private javax.swing.JComboBox jComboBoxStatutClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelClient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNomClient;
    private javax.swing.JTextField jTextFieldPrenomClient;
    // End of variables declaration//GEN-END:variables

    
}
