/*
 * Copyright (C) 2017 cdi415
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Swing;

import Administration.Statut;
import Administration.StatutClient;
import RuntimeException.InvalidCodeNameRuntimeException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cdi415
 */
public class JDialogStatut extends javax.swing.JDialog {

    private String codeType;
    private Statut statutEnCours;
    
    /**
     * Creates new form JDialogStatut
     */
    public JDialogStatut(java.awt.Frame parent, boolean modal, Statut statutEnCours) {
        super(parent, modal);
        setStatutEnCours(statutEnCours);
        initComponents();
    }

    public void setEditionMode(){
        jTextFieldCode.setEnabled(false);
        jTextFieldCode.setText(statutEnCours.getCode());
        jTextFieldDesc.setText(statutEnCours.getInfo());
    }
    
    public String getCodeType() {
        return codeType;
    }

    public void setCodeType(String codeType) {
        jLabelCode.setText("Code " + codeType + " :");
        this.setTitle("Creation d'un nouveau code " + codeType);
        this.codeType = codeType;
    }

    public Statut getStatutEnCours() {
        return statutEnCours;
    }

    private void setStatutEnCours(Statut statutEnCours) {
        this.statutEnCours = statutEnCours;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCode = new javax.swing.JLabel();
        jLabelDesc = new javax.swing.JLabel();
        jTextFieldDesc = new javax.swing.JTextField();
        jTextFieldCode = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelCode.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCode.setText("Code :");
        jLabelCode.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabelDesc.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDesc.setText("Description :");
        jLabelDesc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jButtonOK.setText("Valider");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonOK)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCode)
                            .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDesc)
                            .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonOK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        try{
            if (statutEnCours instanceof StatutClient){
                
            }
            statutEnCours.setCode(jTextFieldCode.getText());
            statutEnCours.setInfo(jTextFieldDesc.getText());
            statutEnCours.save();
            ((JStatutMain)this.getParent()).refresh();
            this.dispose();
        } catch (InvalidCodeNameRuntimeException ex){
            JOptionPane.showMessageDialog(this, 
                    "Veuillez saisir un code valide" 
                            + "\n[errMessage : " 
                            + ex.getMessage() 
                            + "]",
                    "Erreur de saisi", 
                    JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                    "Une erreur SQL est survenu" 
                            + "\n[errMessage : " 
                            + ex.getMessage() 
                            + "]",
                    "SQL Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldDesc;
    // End of variables declaration//GEN-END:variables
}
