/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Administration.Statut;
import Administration.StatutClient;
import Utilisateur.Client;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cdi411
 */
public class JDialogClient extends javax.swing.JDialog {

    private ArrayList<Client> mesClientAEditer;
    
    /**
     * Creates new form JDialogueClient
     */
    public JDialogClient(java.awt.Frame parent, boolean modal, ArrayList<Client> mesClientAEditer) {
        super(parent, modal);
        initComponents();
        
        this.mesClientAEditer = mesClientAEditer;
        
        try {
            jComboBoxStatutClient.addItem(null);
            for (Statut stat : StatutClient.getStatut()){
                jComboBoxStatutClient.addItem(stat);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JClientMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCode = new javax.swing.JLabel();
        jLabelDesc = new javax.swing.JLabel();
        jTextFieldDesc = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jComboBoxStatutClient = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabelCode.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCode.setText("Code :");
        jLabelCode.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelCode);
        jLabelCode.setBounds(10, 12, 79, 16);

        jLabelDesc.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDesc.setText("Description :");
        jLabelDesc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelDesc);
        jLabelDesc.setBounds(10, 38, 79, 16);

        jTextFieldDesc.setEditable(false);
        getContentPane().add(jTextFieldDesc);
        jTextFieldDesc.setBounds(107, 37, 245, 30);

        jButtonOK.setText("Valider");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOK);
        jButtonOK.setBounds(370, 11, 70, 60);

        jComboBoxStatutClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatutClientActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxStatutClient);
        jComboBoxStatutClient.setBounds(110, 10, 240, 20);

        setSize(new java.awt.Dimension(467, 118));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        
        try {
            for (Client monClient : mesClientAEditer) {
                Statut monStatut = ((Statut) jComboBoxStatutClient.getSelectedItem());
                if (monStatut == null){
                    monClient.setStatutClient("");
                } else {
                    monClient.setStatutClient(monStatut.getCode());
                }
                monClient.modifierClient();
            }
            
            this.dispose();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error SQL : \n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonOKActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ((JClientMain)getParent()).refreshJtable();
    }//GEN-LAST:event_formWindowClosed

    private void jComboBoxStatutClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatutClientActionPerformed
        // TODO add your handling code here:
        Statut monStat = (Statut) jComboBoxStatutClient.getSelectedItem();
        jTextFieldDesc.setText(monStat.getInfo());
    }//GEN-LAST:event_jComboBoxStatutClientActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxStatutClient;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JTextField jTextFieldDesc;
    // End of variables declaration//GEN-END:variables
}
