/*
 * Copyright (C) 2017 cdi415
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Swing;

import Evenement.Evenement;
import Exception.EmptyBookEventSQLException;
import Exception.InvalidInputException;
import RuntimeException.InvalidNameRuntimeException;
import bookStore.Livre;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author cdi415
 */
public class JDialogEvent extends javax.swing.JDialog {

    private Action delete = new AbstractAction()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            // get affected table
            javax.swing.JTable table = (javax.swing.JTable)e.getSource();
            // get affected row
            int clickedRow = Integer.valueOf( e.getActionCommand() );
            
            if (clickedRow == 0){ // Ajout de livre
                if (myJDialogEventBook == null){
                    myJDialogEventBook = new JDialogEventBook(self, false);
                    myJDialogEventBook.setVisible(true);
                } else if(!myJDialogEventBook.isVisible()){
                    myJDialogEventBook = new JDialogEventBook(self, false);
                    myJDialogEventBook.setVisible(true);
                }
                
                
            } else {
                // suppression de livre
                //(myEvent.getLivres()).remove(clickedRow-1);
                ((DefaultTableModel)table.getModel()).removeRow(clickedRow);
            }
        }
    };
    
    private JDialogEvent self;
    private JDialogEventBook myJDialogEventBook= null;
    private Evenement myEvent;
    
    private ImageIcon icon_del;
    private ImageIcon icon_add;
    /**
     * Creates new form JDialogEvent
     */
    public JDialogEvent(java.awt.Frame parent, boolean modal, Evenement evenement) {
        super(parent, modal);
        myEvent = evenement;
        
        if (myEvent.getId().equals(0)){
            setTitle("Création d'un nouvel événement");
        } else {
            setTitle("Modification d'un événement");
        }
        
        self = this;
        initIcons();
        initComponents();
        
        
        
    }
    
    private void initIcons(){
        icon_del = null;
        icon_add = null;
        try {
            icon_del = new ImageIcon(getClass().getClassLoader().getResource("resources/images/icon_close_30.png"));
            icon_add = new ImageIcon(getClass().getClassLoader().getResource("resources/images/icon_add_30.png"));
        } catch (java.lang.NullPointerException ex) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldReduc = new javax.swing.JTextField();
        jTextFieldCodePromo = new javax.swing.JTextField();
        jTextFieldDesc = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDateChooserDebut = new com.toedter.calendar.JDateChooser();
        jDateChooserFin = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaComment = new javax.swing.JTextArea();
        jCheckBoxPromo = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLivre = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaLieu = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1000, 782));
        setMinimumSize(new java.awt.Dimension(580, 782));
        setPreferredSize(new java.awt.Dimension(683, 782));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nom : ");
        jLabel2.setFocusable(false);
        jLabel2.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel2.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel2.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Description : ");
        jLabel3.setFocusable(false);
        jLabel3.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel3.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel3.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Code Promo : ");
        jLabel1.setFocusable(false);
        jLabel1.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel1.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel1.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("%");
        jLabel4.setFocusable(false);
        jLabel4.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel4.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel4.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Promo Immédiate : ");
        jLabel5.setFocusable(false);
        jLabel5.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel5.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel5.setPreferredSize(new java.awt.Dimension(155, 155));

        if (myEvent.getReduction()==null){
            jTextFieldReduc.setText("");
        } else {
            jTextFieldReduc.setText(myEvent.getReduction().toString());
        }

        jTextFieldCodePromo.setText(myEvent.getCodePromo());

        jTextFieldDesc.setText(myEvent.getDescription());

        jTextFieldNom.setText(myEvent.getNom());

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Date entrée en poste : ");
        jLabel6.setFocusable(false);
        jLabel6.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel6.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel6.setPreferredSize(new java.awt.Dimension(155, 155));

        jDateChooserDebut.setDateFormatString("yyyy-MM-dd");
        if (myEvent.getDateDebut() != null){
            jDateChooserDebut.setDate(java.util.Date.from((myEvent.getDateDebut()).atStartOfDay(ZoneId.systemDefault()).toInstant()));
        }

        jDateChooserFin.setDateFormatString("yyyy-MM-dd");
        if (myEvent.getDateFin()!= null){
            jDateChooserFin.setDate(java.util.Date.from((myEvent.getDateFin()).atStartOfDay(ZoneId.systemDefault()).toInstant()));
        }

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Date sortie de poste : ");
        jLabel9.setFocusable(false);
        jLabel9.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel9.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel9.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Commantaire : ");
        jLabel10.setFocusable(false);
        jLabel10.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel10.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel10.setPreferredSize(new java.awt.Dimension(155, 155));

        jTextAreaComment.setColumns(20);
        jTextAreaComment.setRows(5);
        jTextAreaComment.setText(myEvent.getCommentaire());
        jScrollPane1.setViewportView(jTextAreaComment);

        jCheckBoxPromo.setSelected(myEvent.getPromoImmediat());
        jCheckBoxPromo.setText("Oui, afficher le directement sur l'article.");

        refreshTable();
        jScrollPane2.setViewportView(jTableLivre);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Par livres", jPanel1);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Prochainement.....");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Par auteurs", jPanel2);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Prochainement.....");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Par editeurs", jPanel3);

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Reduction Promo : ");
        jLabel11.setFocusable(false);
        jLabel11.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel11.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel11.setPreferredSize(new java.awt.Dimension(155, 155));

        jTextAreaLieu.setColumns(20);
        jTextAreaLieu.setRows(5);
        jTextAreaLieu.setText(myEvent.getLieu());
        jScrollPane3.setViewportView(jTextAreaLieu);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Lieu de l'événement : ");
        jLabel12.setFocusable(false);
        jLabel12.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel12.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel12.setPreferredSize(new java.awt.Dimension(155, 155));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jTextFieldDesc))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldCodePromo))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBoxPromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jDateChooserDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jDateChooserFin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldReduc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodePromo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldReduc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxPromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserFin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jTabbedPane1))
        );

        setSize(new java.awt.Dimension(522, 820));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed

        try {
            myEvent.setNom(jTextFieldNom.getText());
            myEvent.setDescription(jTextFieldDesc.getText());
            myEvent.setCodePromo(jTextFieldCodePromo.getText());
            myEvent.setReduction(Float.valueOf(jTextFieldReduc.getText()));
            myEvent.setPromoImmediat(jCheckBoxPromo.isSelected());
            
            if (jDateChooserDebut.getDate() == null){
                throw new InvalidInputException("Merci de fournir une date de début d'événement");
            } else {
                LocalDate myDate = date2LocalDate(jDateChooserDebut.getDate());
                myEvent.setDateDebut(myDate);
            }
            
            if (jDateChooserFin.getDate() != null){
                if ((jDateChooserDebut.getDate()).after(jDateChooserFin.getDate())){
                    throw new InvalidInputException("Merci de fournir une date "
                            + "d'entrée et fin d'événement cohèrente");
                }
                LocalDate myDate = date2LocalDate(jDateChooserFin.getDate());
                myEvent.setDateFin(myDate);
            } else {
                myEvent.setDateFin(null);
            }
            
            myEvent.setCommentaire(jTextAreaComment.getText());
            
            if (jTableLivre.getRowCount() <= 1){
                throw new EmptyBookEventSQLException("Merci de renseigner au moins un livre");
            }
            
            myEvent.clearLivre();
            for (int i=1; i<jTableLivre.getRowCount(); i++){
                myEvent.addLivre((Livre) jTableLivre.getValueAt(i, 0));
            }
            
            myEvent.save();
            
            myEvent.saveBookList();
            
            
            ((JEvent)getParent()).refreshTable();
            this.dispose();
            
        } catch (InvalidInputException | 
                EmptyBookEventSQLException |
                InvalidNameRuntimeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur de saisie", JOptionPane.WARNING_MESSAGE);
        } catch (NumberFormatException ex){
            String msg = "Merci de saisir un nombre valide";
            JOptionPane.showMessageDialog(this, msg, "Erreur de saisie", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur SQL", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    protected void refreshTable (){
        jTableLivre.setModel(initEventTable());
        jTableLivre.getColumnModel().getColumn(0).setMinWidth(0);
        jTableLivre.getColumnModel().getColumn(0).setMaxWidth(0);
        
        TableColumn iconColumn = jTableLivre.getColumnModel().getColumn(jTableLivre.getColumnModel().getColumnCount()-1);
        iconColumn.setMinWidth(40);
        iconColumn.setMaxWidth(40);
        ButtonColumn buttonColumn = new ButtonColumn(jTableLivre, delete, iconColumn.getModelIndex());
        
        //ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("resources/images/icon_edit_30.png"));
        
        jTableLivre.setGridColor(Color.cyan);
        jTableLivre.setShowGrid(true);
        jTableLivre.setShowHorizontalLines(true);
        jTableLivre.setShowVerticalLines(false);
        jTableLivre.setRowHeight(40);
    }
    
    private DefaultTableModel initEventTable(){
        
        DefaultTableModel tableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               if (column == jTableLivre.getColumnModel().getColumnCount()-1){
                   return true;
               }
               
               return false;
            }
        };
        
        tableModel.addColumn("");
        tableModel.addColumn("ISBN");
        tableModel.addColumn("Titre");
        tableModel.addColumn("Sous-Titre");
        tableModel.addColumn("");
        
        Vector vec = new Vector();
        vec.add("");
        vec.add("");
        vec.add("");
        vec.add("");
        if (icon_add == null) {
            vec.add("Add");
        } else {
            vec.add(icon_add);
        }
        tableModel.addRow(vec);
        
        for (Livre book : myEvent.getLivres()){
            vec = new Vector();
            vec.add(book);
            vec.add(book.getIsbnLivre());
            vec.add(book.getTitreLivre());
            vec.add(book.getSousTitreLivre());
            if (icon_del == null) {
                vec.add("Del");
            } else {
                vec.add(icon_del);
            }
            tableModel.addRow(vec);
        }
        
        return tableModel;
    }
    
    private java.time.LocalDate date2LocalDate(java.util.Date date){
        return date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }

    public void addRow(Livre monLivre){
        if (!isLivreInTable(monLivre)){
            Vector vec = new Vector();
                vec.add(monLivre);
                vec.add(monLivre.getIsbnLivre());
                vec.add(monLivre.getTitreLivre());
                vec.add(monLivre.getSousTitreLivre());
                if (icon_del == null) {
                    vec.add("Del");
                } else {
                    vec.add(icon_del);
                }
            DefaultTableModel model = (DefaultTableModel) jTableLivre.getModel();
            model.addRow(vec);
        }
    }
    
    private Boolean isLivreInTable(Livre monLivre){
        
        for (int i=1; i<jTableLivre.getRowCount(); i++){
            if (((Livre)jTableLivre.getValueAt(i, 0)).getIsbnLivre().equals(monLivre.getIsbnLivre())){
                return true;
            }
        }
        
        return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValider;
    private javax.swing.JCheckBox jCheckBoxPromo;
    private com.toedter.calendar.JDateChooser jDateChooserDebut;
    private com.toedter.calendar.JDateChooser jDateChooserFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableLivre;
    private javax.swing.JTextArea jTextAreaComment;
    private javax.swing.JTextArea jTextAreaLieu;
    private javax.swing.JTextField jTextFieldCodePromo;
    private javax.swing.JTextField jTextFieldDesc;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldReduc;
    // End of variables declaration//GEN-END:variables
}
