/*
 * Copyright (C) 2017 cdi415
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Swing;

import Administration.Employe;
import Exception.InvalidEmployeException;
import Exception.InvalidInputException;
import RuntimeException.InvalidEmailException;
import RuntimeException.InvalidNameRuntimeException;
import RuntimeException.InvalidPasswordException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cdi415
 */
public class JDialogAddAdmin extends javax.swing.JDialog {

    private Employe monEmploye;
    
    /**
     * Creates new form JDialogAddAdmin
     */
    public JDialogAddAdmin(java.awt.Frame parent, boolean modal, Employe empl) {
        super(parent, modal);
        monEmploye = empl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldLogin = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jTextFieldemailConfirm = new javax.swing.JTextField();
        jTextFieldMdp = new javax.swing.JTextField();
        jTextFieldMdpConfirm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooserDebut = new com.toedter.calendar.JDateChooser();
        jDateChooserFin = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(155, 155));
        setMinimumSize(new java.awt.Dimension(155, 155));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(155, 155));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nom d'utilisateur : ");
        jLabel1.setFocusable(false);
        jLabel1.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel1.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel1.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nom : ");
        jLabel2.setFocusable(false);
        jLabel2.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel2.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel2.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Prènom : ");
        jLabel3.setFocusable(false);
        jLabel3.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel3.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel3.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Adresse e-mail : ");
        jLabel4.setFocusable(false);
        jLabel4.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel4.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel4.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Confirmer e-mail : ");
        jLabel5.setFocusable(false);
        jLabel5.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel5.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel5.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Date entrée en poste : ");
        jLabel6.setFocusable(false);
        jLabel6.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel6.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel6.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("confirmation Mdp : ");
        jLabel7.setFocusable(false);
        jLabel7.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel7.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel7.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Mot de passe : ");
        jLabel8.setFocusable(false);
        jLabel8.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel8.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel8.setPreferredSize(new java.awt.Dimension(155, 155));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Date sortie de poste : ");
        jLabel9.setFocusable(false);
        jLabel9.setMaximumSize(new java.awt.Dimension(155, 155));
        jLabel9.setMinimumSize(new java.awt.Dimension(155, 155));
        jLabel9.setPreferredSize(new java.awt.Dimension(155, 155));

        jTextFieldNom.setText(monEmploye.getNomEmploye());

        jTextFieldPrenom.setText(monEmploye.getPrenomEmploye());

        jTextFieldLogin.setText(monEmploye.getLoginEmploye());

        jTextFieldemail.setText(monEmploye.getEmailEmploye());

        jTextFieldMdp.setText(monEmploye.getMdpEmploye());

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooserDebut.setDateFormatString("yyyy-MM-dd");
        if (monEmploye.getDebutPosteEmploye() != null){
            jDateChooserDebut.setDate(java.util.Date.from((monEmploye.getDebutPosteEmploye()).atStartOfDay(ZoneId.systemDefault()).toInstant()));
        }

        jDateChooserFin.setDateFormatString("yyyy-MM-dd");
        if (monEmploye.getFinPosteEmploye()!= null){
            jDateChooserFin.setDate(java.util.Date.from((monEmploye.getFinPosteEmploye()).atStartOfDay(ZoneId.systemDefault()).toInstant()));
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNom))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldemailConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMdpConfirm)
                            .addComponent(jDateChooserDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldemailConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMdpConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(421, 401));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(monEmploye.getIdEmploye());
        try {
            monEmploye.setNomEmploye(jTextFieldNom.getText());
            monEmploye.setPrenomEmploye(jTextFieldPrenom.getText());
            monEmploye.setLoginEmploye(jTextFieldLogin.getText());
            
            // Champs obligatoir pour tous nouveau employé
            if (monEmploye.getIdEmploye().equals(0)){
                if (jTextFieldemail.getText().equals("")) {
                    throw new InvalidInputException("Adresse e-mail obligatoire");
                }
                if (!jTextFieldemailConfirm.getText().equals(jTextFieldemail.getText())){
                    throw new InvalidInputException("Adresse mail non identique à la confirmation");
                }
                if (jTextFieldMdp.getText().equals("")) {
                    throw new InvalidInputException("Mot de passe obligatoire");
                }
                if (!jTextFieldMdpConfirm.getText().equals(jTextFieldMdp.getText())){
                    throw new InvalidInputException("Mot de passe non identique à la confirmation");
                }
            }
            
            if (!jTextFieldemailConfirm.getText().equals("")) {
                if (jTextFieldemailConfirm.getText().equals(jTextFieldemail.getText())){
                    monEmploye.setEmailEmploye(jTextFieldemail.getText());
                } else {
                    throw new InvalidInputException("Adresse mail non identique à la confirmation");
                }
            }
            
            if (!jTextFieldMdpConfirm.getText().equals("")) {
                if (jTextFieldMdpConfirm.getText().equals(jTextFieldMdp.getText())){
                    monEmploye.setMdpEmploye(jTextFieldMdp.getText());
                    monEmploye.encodeMdpEmploye();
                } else {
                    throw new InvalidInputException("Mot de passe non identique à la confirmation");
                }
            }
            
            
            if (jDateChooserDebut.getDate() == null){
                throw new InvalidInputException("Merci de fournir une date d'entrée en service");
            } else {
                LocalDate myDate = date2LocalDate(jDateChooserDebut.getDate());
                monEmploye.setDebutPosteEmploye(myDate);
            }
            
            if (jDateChooserFin.getDate() != null){
                if ((jDateChooserDebut.getDate()).after(jDateChooserFin.getDate())){
                    throw new InvalidInputException("Merci de fournir une date "
                            + "d'entrée et fin de service cohèrente");
                }
                LocalDate myDate = date2LocalDate(jDateChooserFin.getDate());
                monEmploye.setFinPosteEmploye(myDate);
            } else {
                monEmploye.setFinPosteEmploye(null);
            }
            
            monEmploye.save();
            ((JAdmin)getParent()).refreshTable();
            this.dispose();
        }
        //catch (Exception ex){ex.printStackTrace();}
        catch (InvalidEmployeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur d'organisation", JOptionPane.ERROR_MESSAGE);
        } catch (InvalidInputException 
                | InvalidPasswordException 
                | InvalidEmailException 
                | InvalidNameRuntimeException
                ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur de saisie", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur SQL", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private java.time.LocalDate date2LocalDate(java.util.Date date){
        return date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooserDebut;
    private com.toedter.calendar.JDateChooser jDateChooserFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldMdp;
    private javax.swing.JTextField jTextFieldMdpConfirm;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldemailConfirm;
    // End of variables declaration//GEN-END:variables
}
