/*
 * Copyright (C) 2017 cdi415
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Swing;

import Evenement.Evenement;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author cdi415
 */
public class JEvent extends javax.swing.JFrame {

    private Action buttonClicked = new AbstractAction()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            // get affected table
            javax.swing.JTable table = (javax.swing.JTable)e.getSource();
            // get affected row
            int clickedRow = Integer.valueOf( e.getActionCommand() );
            
            if (clickedRow == 0){
                new JDialogEvent(self, true, new Evenement()).setVisible(true);
            } else {
                new JDialogEvent(self, true, (Evenement) table.getValueAt(clickedRow, 0)).setVisible(true);
            }
        }
    };
    
    private JEvent self;
    
    /**
     * Creates new form JEvent
     */
    public JEvent() {
        self = this;
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 200));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        refreshTable();
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(911, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

       protected void refreshTable (){
        jTable.setModel(initEventTable());
        jTable.getColumnModel().getColumn(0).setMinWidth(0);
        jTable.getColumnModel().getColumn(0).setMaxWidth(0);
        
        jTable.getColumnModel().getColumn(1).setMinWidth(100);
        
        
        jTable.getColumnModel().getColumn(3).setMinWidth(10);
        jTable.getColumnModel().getColumn(3).setMaxWidth(110);
        jTable.getColumnModel().getColumn(3).setWidth(110);
        
        jTable.getColumnModel().getColumn(4).setMinWidth(10);
        jTable.getColumnModel().getColumn(4).setMaxWidth(110);
        jTable.getColumnModel().getColumn(4).setWidth(110);
        
        TableColumn iconColumn = jTable.getColumnModel().getColumn(jTable.getColumnModel().getColumnCount()-1);
        iconColumn.setMinWidth(40);
        iconColumn.setMaxWidth(40);
        ButtonColumn buttonColumn = new ButtonColumn(jTable, buttonClicked, iconColumn.getModelIndex());
        
        jTable.setGridColor(Color.LIGHT_GRAY);
        jTable.setShowGrid(true);
        jTable.setShowHorizontalLines(true);
        jTable.setShowVerticalLines(false);
        jTable.setRowHeight(40);
    }
    
    private DefaultTableModel initEventTable(){
        
        DefaultTableModel tableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               
               if (column == jTable.getColumnModel().getColumnCount()-1){
                   return true;
               }
               
               return false;
            }
        };
        
        tableModel.addColumn("");
        tableModel.addColumn("Nom");
        tableModel.addColumn("Description");
        tableModel.addColumn("Date de début");
        tableModel.addColumn("Date de fin");
        tableModel.addColumn("Code Promo");
        tableModel.addColumn("");
        
        ImageIcon icon_edit = null;
        ImageIcon icon_add = null;
        try {
            icon_edit = new ImageIcon(getClass().getClassLoader().getResource("resources/images/icon_edit_30.png"));
            icon_add = new ImageIcon(getClass().getClassLoader().getResource("resources/images/icon_add_30.png"));
        } catch (java.lang.NullPointerException ex) {}
        
        Vector vec = new Vector();
        vec.add("");
        vec.add("");
        vec.add("");
        vec.add("");
        vec.add("");
        vec.add("");
        if (icon_add == null) {
            vec.add("Add");
        } else {
            vec.add(icon_add);
        }
        tableModel.addRow(vec);
        
        for (Evenement event : Evenement.getArrayListAllEvenement()){
            vec = new Vector();
            vec.add(event);
            vec.add(event.getNom());
            vec.add(event.getDescription());
            vec.add(event.getDateDebut().format(DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)));
            if (event.getDateFin() != null){
                vec.add(event.getDateFin().format(DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)));
            } else {
                vec.add("");
            }
            
            vec.add(event.getCodePromo());
            if (icon_edit == null) {
                vec.add("E");
            } else {
                vec.add(icon_edit);
            }
            
            tableModel.addRow(vec);
        }
        
        return tableModel;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
