/*
 * Copyright (C) 2017 cdi411
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Swing;

import Administration.Employe;
import Exception.InvalidInputException;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cdi411
 */
public class JLog extends javax.swing.JFrame {

    /**
     * Creates new form JLog
     */
    private JGestion jdGestion;
   

    public JLog() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogin = new javax.swing.JLabel();
        jLabelMdp = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jTextFieldMdp = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelLogin.setText("Login");
        getContentPane().add(jLabelLogin);
        jLabelLogin.setBounds(20, 40, 80, 50);

        jLabelMdp.setText("Mot de passe");
        getContentPane().add(jLabelMdp);
        jLabelMdp.setBounds(20, 110, 90, 30);

        jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLogin);
        jTextFieldLogin.setBounds(129, 50, 130, 30);
        getContentPane().add(jTextFieldMdp);
        jTextFieldMdp.setBounds(129, 110, 130, 30);

        jButtonOk.setText("OK");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOk);
        jButtonOk.setBounds(210, 160, 47, 23);

        setBounds(0, 0, 306, 265);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        if (jTextFieldLogin.getText().equals("")) {
            try {
                throw new InvalidInputException("Login obligatoire");
            } catch (InvalidInputException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur SQL", JOptionPane.ERROR_MESSAGE);
            }

        }
        if (jTextFieldMdp.getText().equals("")) {
            try {
                throw new InvalidInputException("Mot de passe obligatoire");
            } catch (InvalidInputException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur SQL", JOptionPane.ERROR_MESSAGE);
            }
        }

        try {
            if (Employe.exists(jTextFieldLogin.getText(), SqlManager.SqlManager.encodeString(jTextFieldMdp.getText()))) {
                System.out.println("OK");
                if (jdGestion == null) {
                    jdGestion = new JGestion();
                    jdGestion.setVisible(true);
                } else if (!jdGestion.isVisible()) {
                    jdGestion = new JGestion();
                    jdGestion.setVisible(true);
                } else if (jdGestion.getState() == Frame.ICONIFIED) {
                    jdGestion.setState(Frame.NORMAL);
                } else {
                    jdGestion.toFront();
                }
               
            } else {
                System.out.println("NON OK");
                try {
                throw new InvalidInputException("mot de passe et/ou login faux");
            } catch (InvalidInputException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur SQL", JOptionPane.ERROR_MESSAGE);
            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(JLog.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelMdp;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldMdp;
    // End of variables declaration//GEN-END:variables
}
